### ISSUE TITLE
Foreign primary key support

### ISSUE THREAD

**Issue by aivus** [sonata-project/EntityAuditBundle#121]
When I use [foreign primary key](http://doctrine-orm.readthedocs.org/en/latest/tutorials/composite-primary-keys.html) I get

```
Notice: Undefined index: id in /var/www/ekipazh/vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php line 364
```

**Comment by aivus** [comment]
Here is:
* https://raw.githubusercontent.com/aivus/symfony2-foreign-bug/master/src/App/AppBundle/Resources/config/doctrine/CouponToOrder.orm.yml
* https://github.com/aivus/symfony2-foreign-bug/blob/master/src/App/AppBundle/Resources/config/doctrine/RealOrder.orm.yml
* https://github.com/aivus/symfony2-foreign-bug/blob/master/src/App/AppBundle/Resources/config/doctrine/Order.orm.yml

**Comment by DavidBadura** [comment]
@aivus can you **please** test the master again? I hope the problem has been fixed. Thanks!

**Comment by aivus** [comment]
@DanielBadura sorry, but I can't test it again.

**Comment by DanielBadura** [comment]
@DavidBadura ping ^^
