### ISSUE TITLE
Getting error when we drop schema

### ISSUE THREAD

**Issue by amitblues123** [sonata-project/EntityAuditBundle#128]
When we are using dev-master then we are getting below error while we drop the schema.
Please can you help us on this.
I have raised the error  "sequence not found" and in the dev-master issues is fixed but now we are getting this error.
Note : we are using Oracle database.

[Doctrine\ORM\Tools\ToolsException]     :      Schema-Tool failed with Error 'An exception occurred while executing 'CREATE SEQUENCE REVISIONS_SEQ START WITH 1 MINVALUE 1 INCREMENT BY 1  
  ':    ORA-00955: name is already used by an existing object' while executing DDL: CREATE SEQUENCE REVISIONS_SEQ START WITH 1 MINVALUE 1 INCREMEN  
  T BY 1                                                                                                                                      

  [Doctrine\DBAL\Exception\TableExistsException]  
  An exception occurred while executing 'CREATE SEQUENCE REVISIONS_SEQ START WITH 1 MINVALUE 1 INCREMENT BY 1':    ORA-00955: name is already used by an existing object  
  [Doctrine\DBAL\Driver\OCI8\OCI8Exception]   ORA-00955: name is already used by an existing object

**Comment by andrewtch** [comment]
Around a month or so the sequency behavior was changed, most probably you'll have to drop it yourself.

**Comment by amitblues123** [comment]
Yes, now we are dropping the sequence manually. But this issue will be fixed in later version?
Because when we move to live environment dropping the sequence will not good idea or suggest us the another solution.
