### ISSUE TITLE
Audit viewer not showing BOOLEAN changes

### ISSUE THREAD

**Issue by guidolodetti** [sonata-project/EntityAuditBundle#144]
In the /audit viewer, the table of changes isn't showing the differences in boolean values (they are blank!).
In the audit database all the values are stored correctly.

**Comment by tolry** [comment]
@guidolodetti are you talking about the frontend (twig templates) or the AuditReader?

**Comment by guidolodetti** [comment]
Hello @tolry, I'm talking about the twig templates!

**Comment by guidolodetti** [comment]
Hello @tolry! Seems like the bug was much bigger: in v0.7, all fields like "customName" or "lowerToUpper" where converted to lower case ("customname", "lowertoupper"), and so where unreachable. I have made a pull request to fix this bug in v0.7.

Thanks

**Comment by DavidBadura** [comment]
> I have made a pull request to fix this bug in v0.7.

I can not find your PR. Can you give me the link?
