### ISSUE TITLE
Clean history

### ISSUE THREAD

**Issue by Th3Mouk** [sonata-project/EntityAuditBundle#158]
Probably a must have, actually some of my databases get more than 20000 revisions.

Add a command, to remove major (outdated) of them, by selecting the number to keep or the date of expiration, and tables concerned, must be interesting.

**Comment by OskarStark** [comment]
:+1:

**Comment by soerenbernstein** [comment]
I have written a cleanup script for a project as symfony console command. If anyone is interested, I could provide it.

**Comment by OskarStark** [comment]
please @soerenbernstein

**Comment by zhukovra** [comment]
@soerenbernstein can you gist it?

**Comment by soerenbernstein** [comment]
Here my cleanup script. This will remove all entity revisions which doesn't reflect any tracked changes. After that it will remove all revisions from the revision table which no longer have any changed entities.

https://gist.github.com/soerenbernstein/e0bf825ace65659da5ae8bb0dd63cfdd

**Comment by rvanlaak** [comment]
Having a cleanup command that allows to archive revisions that are more than 1yr old would be great. 

We have an entity that gets saved via XHR 10 seconds after the user changes the input, so these entities have lots of revisions that are not useful. Another scenario would be to have an option to remove all revisions between an entity's first and latest revision.

**Comment by Soullivaneuh** [comment]
Also interested. Another id would be to be able to clean revision related to a specific field of an entity.

Would be useful for a field we forgot to ignore for example.

**Comment by Soullivaneuh** [comment]
@soerenbernstein Can you please explain why you create a new table and remove the old one on `cleanupEntityRevisions` instead of simply removing not needed rows?

**Comment by soerenbernstein** [comment]
I do this to prevent a total loss of all revisions in case something goes horribly wrong.

**Comment by soerenbernstein** [comment]
@Soullivaneuh Btw. the linked script will remove revisions that only change ignored columns.
