### ISSUE TITLE
Revert to revision 'x'

### ISSUE THREAD

**Issue by INHack20** [sonata-project/EntityAuditBundle#172]
Hello, currently use this library is very good, congratulations.
It might include the option to revert the changes from one entity to a specific version?

SimpleThings\EntityAudit\AuditReader
public function revert($object, $revision);

Thanks

**Comment by tolry** [comment]
Hi @INHack20,

thanks for the praise and your suggestion. We have to be careful to not reimplement something like git at this point. Meaning "reverting" should probably do one of the following things

* load the given revision, persist the object and discard all "future" revisions (not my favorite)
* load the given revision, persist the object, resulting in a new revision that holds the same data as the old revision (this can be easily done right now already)

We should - imo - not start thinking about having a chain of revisions, that are linked to each other. In which case reverting would traverse back to an old revision and attaching new revisions as changes are made. Leaving the old histort, before the revert intact, effectively spanning a graph, like git.

On another note, AuditReader is probably not the best place to put the revert method: revert is a write operation.

I would prefer a helper class that simplifies what's already possible:

* find specified revision
* transfer data in original doctrine entity
* persist said entity, resulting in a new revision

Generally speaking, EntityAudit should keep write operations on entities to a minimum (hence the name, audit) - but this would be more or less a little helper method, which is fine by me.

Other opinions on this? @DavidBadura @smoench

**Comment by tolry** [comment]
btw: you are of course welcome to create a PR for this, if you like

**Comment by INHack20** [comment]
Hi, thanks for your comments.

I personally like the option:

"load the given revision, persist the object, resulting in a new revision that holds the same data as the old revision (this can be easily done right now already)"

Where you recommend placing the method to revert changes?

**Comment by severin-bruhat** [comment]
Hi,
What's the status of this feature? That would be really great if we could restore an entity to a specific revision.

Thanks
