### ISSUE TITLE
Issue with composite primary key

### ISSUE THREAD

**Issue by RomainCXP** [sonata-project/EntityAuditBundle#191]
Hi,

I'm using your bundle with Symfony 2 and Doctrine and I have an entity with a composite primary key where one of it is another entity: 

``` php
class MyClass
{
    /**
     * @var Project\MyBundle\Entity\MyEntity
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="Project\MyBundle\Entity\MyEntity", inversedBy="MyClass")
     * @ORM\JoinColumn(name="my_entity_id", referencedColumnName="id")
     */
    private $myEntity;
    /**
     * @var integer
     * @ORM\Id
     * @ORM\Column(name="my_integer", type="integer")
     */
    private $myInteger;
...
}
```

The issue here is when i try to delete 'MyClass' i get this exception : 
`Warning: spl_object_hash() expects parameter 1 to be object, string given in vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php at line 1540`

After investigation it seems that in the final array_merge() in onFlush() from the listener SimpleThings\EntityAudit\EventListener\LogRevisionsListener,  the object'myEntity' is replaced by the value of its id and therefore doctrine can't save it : 
`$entityData = array_merge($this->getOriginalEntityData($entity), $this->uow->getEntityIdentifier($entity));`

I tried to change the order of the merge :  `$entityData = array_merge($this->uow->getEntityIdentifier($entity),$this->getOriginalEntityData($entity));` and it worked for my case. Is there a particular reason for this merge to have this specific order or can it be changed ? 

For the same reasons, it seems the postFlush() function throws an error because of how the SQL code is built for the extra updates.  $columnName is assumed to always be a string while in my case it is an array.

Thank you.

**Comment by mrtnzagustin** [comment]
@RomainCXP are u still using this bundle? did  you fork it to make that changes? im having the same issue
