### ISSUE TITLE
Manage user id with foreign key and object instance

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/EntityAuditBundle#224]
Saving username is great because it works with all Symfony security implementation.

But be based on username can be a problem. On some application, username can be changed.

I think we should consider an optional way to manage user id linked to user instance, like for FOSUser generated ones.

**Comment by Soullivaneuh** [comment]
It's a start but you will just have an integer inside the `username` column. 

You won't get the doctrine relations benefit with this.

**Comment by Soullivaneuh** [comment]
@tseho Good catch but it would be better to have this configurable. :wink:
