### ISSUE TITLE
is EntityAudit a bundle or a library ?

### ISSUE THREAD

**Issue by tseho** [sonata-project/EntityAuditBundle#226]
Globally, there is something we need to clarify, is EntityAudit a bundle or a library we can use as a standalone ?

for example, the class `AuditConfiguration` contains the method 

```
    public static function forEntities(array $classes)
    {
        $conf = new self;
        $conf->auditedEntityClasses = $classes;

        return $conf;
    }
```

But this class is also configured as a service `simplethings_entityaudit.configsimplethings_entityaudit.config`

I don't think the static creation is a good practice (please correct me if I'm wrong), it's only used in tests and it has been proven really annoying to inject dynamic configuration (Annotated entities for exemple) with the way the current AuditConfiguration works.

Are we keeping the project oriented as a static/standalone library ?

**Comment by tolry** [comment]
@tseho currently EntityAudit is both, which has historic reasons: back then people didn't separate libs from the bundle. I would very much prefer for this to be split up, but this would require quite a bit of work, which e.g. I do not have the time nor knowledge of the inner workings of EntityAudit.

So: splitting in lib + bundle is probably good idea, but I do not see it in the near future. Maybe some kind of CodeSprint might be needed to make this happen?

**Comment by Soullivaneuh** [comment]
@tolry Splitting library and bundle is not *necessarily* a good idea. It's depends of the size of the symfony integrations IMHO.

Example with my lib: https://github.com/Soullivaneuh/IsoCodesValidator

This is a library for symfony validator component (no bundle).

But it also provides a bridge part for Silex and Symfony integration: https://github.com/Soullivaneuh/IsoCodesValidator/tree/3.x/src/Bridge

See the folders. You will see only few classes for services integration and translations.

I split them up before, but I do the reverse later because it's quite overkill to maintain code and push new version of three repositories just for this.

The another solution would be to use a project splitter with read-only project like Symfony does (can't retriew the link of the used tools ATM). But again, for a tiny project like mine, I don't think it really worth it.

Just my two cents. :wink:

**Comment by DavidBadura** [comment]
I think we should split this package. We have not just the integration to the framework, but also controllers and templates. In addition some features are developed with focus on symfony and not on the library (see #233). 

But how can we do this? My idea is:

* rename this repository in EntityAuditBundle (github provide redirects)
* change the repository url on packages.org
* clone this project in a new repository (entity-audit) and change the package name
* remove unrelated code etc.

But what should we with the issues and pr?

**Comment by Soullivaneuh** [comment]
> But how can we do this?

We can also have one repo for writing and split then into many read-only repo.

Symfony does this with this tool: https://github.com/splitsh/lite

> But what should we with the issues and pr?

AFAIK, it's not possible to move a PR or an issue to another project with GitHub.

But if you choose the case with splitsh, this would not be a problem IMO.

**Comment by tseho** [comment]
Renaming the project to EntityAuditBundle makes sense, every bundle out there use the "Bundle" suffix, this will avoid confusion between a standalone library and the bundle.

Since renaming and splitting will be a major BC break (v2.0 ?), does renaming will break users using a existing release with composer ?

I like the idea suggested by @Soullivaneuh about splitting into a read-only repo. It's interesting if @DavidBadura and simplethings want to maintain a standalone library. What about issues ? Do you want to deal with issues into the bundle repository and into the library repository ?

And if the project is separated into two repositories, wouldn't that be easier to just have the bundle having a dependency on the standalone-library ?

**Comment by smoench** [comment]
I have moved bundle related files into a separate folder / namespace with this PR #242.

**Comment by DavidBadura** [comment]
> Since renaming and splitting will be a major BC break (v2.0?)

yes, we are working on 2.0

> does renaming will break users using a existing release with composer?

no, github creates redirects until we use the name "simplethings/EntityAudit" again. But we don't want to use it again, so we should be fine.

> I like the idea suggested by @Soullivaneuh about splitting into a read-only repo. It's interesting if @DavidBadura and simplethings want to maintain a standalone library.

Splitting it into read-only repositories needs more maintenance time. For the 2.0 version we want to focus on a standalone library with a clean api.

**Comment by tolry** [comment]
I think we have two issues here to discuss and talk about them separately:

1. should we split the library and the symfony bundle (and possible future integrations in other frameworks [laravel, zend, ...]) in separate composer packages?
2. how do we organize this in terms of github repositories?

1.) This should be easy: split in separate packages - or does anybody have arguments against this?

2.) 

splitting into multiple repositories:

* pro
  * easy handling with composer
  * version packages easily indipendent from each other
* con
  * issues cannot be moved easily between projects (there are workarounds for this with external scripts)
  * hard to  move code around, retaining git history

monorepo:

* con
  * something like [Composer Monorepo/Plugin](https://github.com/beberlei/composer-monorepo-plugin) ist not (yet?) in composer core and not supported by packagist (as far as I know) and therefore better suited for internal developments
  * readonly repos per "component" are additional maintenance work

I generally like having one repository, but do not know how cumbersome the tooling for the readonly repos would be. For additional arguments pro monorepo take a look at Benjamin's [talk](https://qafoo.com/talks/15_08_froscon_monorepos.pdf) on that matter.

As I see it, a monorepo would need additional resources, as someone would need to install and configure splitsh to be able to make releases. Which might be problematic as we are already stretched thin for maintainers as it is. Making the release process more complicated might not be beneficial to that situation.

So in the end, I am currently leaning toward multiple repositories, as this is probably the quickest way to get the package split realized.

Any other thoughts or pros/cons that I have missed mentioning?

**Comment by tolry** [comment]
additional article on this topic http://www.whitewashing.de/2015/04/11/monolithic_repositories_with_php_and_composer.html

**Comment by DavidBadura** [comment]
If everyone agrees: At the end of the week, I will rename the project to EntityAuditBundle.

**Comment by Soullivaneuh** [comment]
> What about issues ? Do you want to deal with issues into the bundle repository and into the library repository ?

@tseho Issues will be on the main repository. Symfony work like that: https://github.com/symfony/symfony/issues

Other read-only repositories are just part of the main repository, allows user to pick only some part of the framework.

BTW, it will be the same for versions. If you patch something on the bundle part, a new patch version will be released for both library and bundle, even if no modification was made on the library.
This is the principal con of the monorepo IMHO.

> Splitting it into read-only repositories needs more maintenance time.

@DavidBadura It took less time that maintaining multiple repositories manually.

After that, I personally prefer to keep all onto one repo if integrations are not too heavy.

But if you want to split, I think monorepo is the best solution.

Again, just my two cents! :wink:
