### ISSUE TITLE
add official MSSQL support

### ISSUE THREAD

**Issue by DavidBadura** [sonata-project/EntityAuditBundle#260]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

We can not currently provide any official support for MSSQL, as we can not test it. With [AppVeyor](https://www.appveyor.com/) we have the possibility.

Doctrine is attending to integrate AppVeyor (https://github.com/doctrine/dbal/pull/2617). We should just wait until they are done and then we'll take it 😄

**Comment by photodude** [comment]
We did this with Joomla already
https://github.com/joomla/joomla-cms/pull/13790
and the Joomla-Framework Database package
https://github.com/joomla-framework/database/pull/72

The Doctrine DBAL implementation is just different
Note: lots of packages are doing this now

**Comment by photodude** [comment]
Also there are the MSSQL Linux package now so there is a way to do this on Travis CI

>The SQL Server for Linux preview is available as a docker image. Assuming we can setup Travis to protect our access key to the private preview, we could use docker on Travis CI builds to execute against tests SQL Server.
>
> https://www.microsoft.com/en-us/server-cloud/sql-server-on-linux.aspx
>
> https://docs.travis-ci.com/user/docker/

**Comment by photodude** [comment]
Apparently, someone has a workaround for testing Oracle DB on travis ci as well https://github.com/cbandy/travis-oracle

an Oracle account is required and the Oracle username and password has to be in the build environment variables either as hidden repository settings or encrypted variables

**Comment by DavidBadura** [comment]
Amazing! Thanks for the valuable information! I'll try it soon :-)

**Comment by photodude** [comment]
you are welcome

**Comment by photodude** [comment]
FYI Doctrine is working on implementing Oracle testing on the DBAL package using @continuousphp 

https://continuousphp.com

Setup is all done in the account via their web interface. so you are on your own with that.
