### ISSUE TITLE
Installation does not create table

### ISSUE THREAD

**Issue by jenyak** [sonata-project/EntityAuditBundle#268]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

I install master version, register bundle, add annotation to my entity

```
...
use Doctrine\ORM\Mapping as ORM;
use SimpleThings\EntityAudit\Mapping\Annotation as Audit;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ParameterRepository")
 * @Audit\Auditable()
 */
class Parameter
{
...
```
 call the command
`app/console doctrine:schema:update --dump-sql `
but it returned
`Nothing to update - your database is already in sync with the current entity metadata`.
while I expect new tables queries

As I found out that service [simplethings_entityaudit.create_schema_listener](https://github.com/simplethings/EntityAuditBundle/blob/1.0/src/SimpleThings/EntityAudit/Resources/config/auditable.xml#L33) missing in master version, maybe that why update command don't have effect.

**Comment by tolry** [comment]
@jenyak thanks for the report - master branch is *not* stable, please use `^1.0` as version restriction in composer

**Comment by Laniax** [comment]
any update on this?
