### ISSUE TITLE
Syntax error or access violation: 1110 Column 'category_id' specified twice

### ISSUE THREAD

**Issue by Webonaute** [sonata-project/EntityAuditBundle#297]
| Q                | A
| ---------------- | -----
| Bug report?      yes
| Feature request? no
| BC Break report? no

PHP 7.1
Symfony 3.2

I have issue where column are specified twice in the sql query.

**Comment by tolry** [comment]
@Webonaute could you give us a few more informations?

Helpful details

* which exact version of entitybundle are you using
* could you give us your entity definition?
* could you give us the complete query?

thanks

**Comment by Webonaute** [comment]
Its the last release version v1.0.6
it happen when an entity have the column definition like category_id and an association many to one. I know its unusual but this configuration look to save us a lot of load time.

**Comment by tolry** [comment]
@Webonaute doesn't sound unusual at all and generally those associations are supported, as far as I know

Would you mind giving more details (as told above, Entity definition, complete sql query, complete error message, ...), otherwise we will be unable to reproduce this.

**Comment by Webonaute** [comment]
our delivery is very close so for now we only disabled all audit on translation table. I will come back with the needed information soon.
