### ISSUE TITLE
how to test the className in Twig ?

### ISSUE THREAD

**Issue by benbet** [sonata-project/EntityAuditBundle#300]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no

Hi, 

thank's for your magic bundle :-)

In my project, I want to make a history list of revisions and I want to adapt my text in relation of the entity that's modified. To do this I want to check the name of the className in twig like "entity.className == 'bundle\entity\nameEntity', but the test doesn't work. Nothing happens and twig ignore it. 

When I display the className like{{className }}, the class is correctly displaying.

Could you help me ?

Thank's
Regards.

**Comment by W0rma** [comment]
AFAIK twig does not support this out of the box. However you could just add a custom twig extension as describe here: https://stackoverflow.com/a/58419702/7256202
