### ISSUE TITLE
No Mapping/Annotation path after version 1.0.3 

### ISSUE THREAD

**Issue by aibragimov4xxi** [sonata-project/EntityAuditBundle#305]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Used Version     | e.g. 1.0.6

There is no path `Mapping/Annotation` after version 1.0.3

So if you try to use `composer require simplethings/entity-audit-bundle` with Symfony you will have an error in your entity after using 
`use SimpleThings\EntityAudit\Mapping\Annotation as Audit;`

I tried manually install version 1.0.3 but got error: 
`[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                                                                                                     
  You have requested a non-existent parameter "simplethings.entityaudit.audited_entities". Did you mean one of these: "simplethings.entityaudit.entity_manager", "simplethings.entityaudit.table_  
  prefix", "simplethings.entityaudit.table_suffix"?`

Then I tried to install version 1.0.1 but there is no `@Audit\Ignore()` annotation.

Is there any stable working version with `@Audit\Ignore()` annotation?

**Comment by BitScout** [comment]
I found a way to make 1.0.6 work by ignoring the current README.md:
- Revert your entity class. No `use SimpleThings...,` no annotation.
- Add the following (taken from the branch 1.0 README.md) to your config.yml:

```
simple_things_entity_audit:
    audited_entities:
        - AppBundle\Entity\Foo
```

Now `php .\bin\console doctrine:schema:update --dump-sql` will generate the CREATE statement etc. for your `foo` table. (Why does README.md say `./app/console` instead?)

**Comment by Soullivaneuh** [comment]
It looks like it's not wanted.

d6c1c0667a83b0256f907b15ba77e084269042f2 where it is introduced is contained in 1.0.1 and 1.0.3 but not 1.0.2 nor the others.

And if you looks at https://github.com/simplethings/EntityAuditBundle/pull/222, you will see the PR is targeted for 2.0 release.

@DavidBadura Could you please confirm that and give us more information? BTW, did you plan to release 2.0 soon?

**Comment by sulaman0** [comment]
> I found a way to make 1.0.6 work by ignoring the current README.md:
> 
> * Revert your entity class. No `use SimpleThings...,` no annotation.
> * Add the following (taken from the branch 1.0 README.md) to your config.yml:
> 
> ```
> simple_things_entity_audit:
>     audited_entities:
>         - AppBundle\Entity\Foo
> ```
> 
> Now `php .\bin\console doctrine:schema:update --dump-sql` will generate the CREATE statement etc. for your `foo` table. (Why does README.md say `./app/console` instead?)

I've tried by using the mentioned codes but not working.
When I'm inserting new records through the Foo Entity, no record added to the revision table
