### ISSUE TITLE
Wrong behavior with Symfony doctrine:migrations:diff command

### ISSUE THREAD

**Issue by aibragimov4xxi** [sonata-project/EntityAuditBundle#306]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Used Version     | e.g. 1.0.1

I annotated my entity as Auditable, then I tried to use `php bin/console doctrine:migrations:diff` command. 
But in new migration there was many `audit` tables for another entities (which were not auditable) but no table for my auditable entity.

How can I get correct migration from `Auditable` annotation?

**Comment by mattchete** [comment]
@aibragimov4xxi Did you find any solution?

**Comment by emr** [comment]
Same problem here (v1.0.9). But the problem not related to doctrine migrations. I think related to Symfony service container and the `simplethings.entityaudit.audited_entities` parameter bundle's uses.

**Comment by emr** [comment]
I found where `simplethings.entityaudit.audited_entities` parameter is modified.
See: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/DependencyInjection/Compiler/AddAuditEntityCompilerPass.php#L52

`SonataDoctrineORMAdminBundle` modifies it. You can disable this behavior with that bundle's configuration:
```
sonata_doctrine_orm_admin:
    audit:
        force: false
```
