### ISSUE TITLE
Getting private services from container is deprecated since Symfony 3.2

### ISSUE THREAD

**Issue by joshgh** [sonata-project/EntityAuditBundle#307]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| Used Version     | 1.0.6

When accessing the auditReader service as described in the README, the following deprecation notice is thrown by Symfony (I am using Symfony 3.4):
`User Deprecated: The "simplethings_entityaudit.reader" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`

**Comment by W0rma** [comment]
Should have been fixed in https://github.com/simplethings/EntityAuditBundle/pull/316
