### ISSUE TITLE
[question] How to run tests?

### ISSUE THREAD

**Issue by DanielFurmanov** [sonata-project/EntityAuditBundle#309]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| Used Version     | 1.0.6

I have forked and made some changes, How do I run tests? Your phpunit readme says "Currently tests only run in a Symfony2 context.", does that mean that I should install symfony2 and require EntityAuditBundle with composer? How then I run tests for this bundle?

**Comment by tolry** [comment]
where did you fork your branch off? master is currently in a "broken" state (split up of library + bundle in two repositories)

**Comment by DanielFurmanov** [comment]
@tolry I have been using the 1.0.x branch, so it should be ok.
What I actually did - i took some PR from master and implemented it in 1.x branch. Everything is working so far, but I want to be sure that bundle is actually working. Have never encountered the need to run test for specific vendor package... so kinda struggling. Just `phpunit <Audit bundle folder>` doesn't work, fails to load some symfony classes. I can give you more details, but I guess the problem is me, not the code. That why I am asking :)

**Comment by tolry** [comment]
Sorry for not being much of help here, since I haven't run the tests myself (not a real active dev of this package :-) ) - easiest way might be, to submit a PR as "WIP" and let travis do the heavy lifting. Although 1.0-branch seems to have build problems by itself :-/ => https://travis-ci.org/simplethings/EntityAuditBundle

But this seems to be mostly because of a php version problem (5.3 no longer available via travis?)

**Comment by tolry** [comment]
https://github.com/travis-ci/travis-ci/issues/7163 <-- on the php 5.3 issue

**Comment by DanielFurmanov** [comment]
Thank you for the option, created the PR https://github.com/simplethings/EntityAuditBundle/pull/310
Will write in some time, I am currently submitting also PR to my project, so when it will be tested its safe to assume that the bundle is working properly (it should)
