### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by brud** [sonata-project/EntityAuditBundle#314]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| Used Version     | none

May be I'm to naive, but did you planing for supporting Symfony 4 in your bundle?)

**Comment by tolry** [comment]
@brud dev power is quite low at this project (has been for a while) - but I do not see any show stoppers for sf4 (haven't tried it yet) - of course we do not have a fancy flex recipe for now :smile: 

Do you have concrete problems using the bundle with sf4?

**Comment by tolry** [comment]
@brud can you check if everything is working for you with 1.0.8? see #316

**Comment by W0rma** [comment]
This has already been fixed in https://github.com/sonata-project/EntityAuditBundle/pull/347
