### ISSUE TITLE
[RFC] `global_ignore_columns` param should be renamed to `global_ignore_fields`

### ISSUE THREAD

**Issue by phansys** [sonata-project/EntityAuditBundle#329]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| Used Version     | 1.0.9

`global_ignore_columns` param must be renamed to `global_ignore_fields`, since its values are checked against field names instead column names.
I think we could deprecate it, explaining the new one must be used.

**Comment by tolry** [comment]
IIRC both configuration names are working currently, leaving the old (columns) only for compat reasons, but I might be confusing this with another ignore-config variable.

**Comment by tolry** [comment]
found the PR https://github.com/simplethings/EntityAuditBundle/pull/213

**Comment by phansys** [comment]
In latest `1.x` tag (currently [v1.0.9](https://github.com/simplethings/EntityAuditBundle/releases/tag/v1.0.9)), there is just `global_ignore_columns` config option: https://github.com/simplethings/EntityAuditBundle/blob/5725ecab2d132288842d9a075d1a8662520829c5/src/SimpleThings/EntityAudit/DependencyInjection/Configuration.php#L18-L20
#213 was made against `master`, even, that option is currently not part of that branch (https://github.com/simplethings/EntityAuditBundle/commit/2df48c34fc154be744eddf64717a08b0c28be16b#diff-7005d8857f97a86a6140690466b7723f).

**Comment by tolry** [comment]
Hmm, I could have sworn, that PR was older than the 1.x-branch, sorry about the confusion. I guess it's time to decide about master branch being reverted to/merged with 1.x to avoid a complete halt in development.

Last I heard from @DavidBadura it sounded, like he wouldn't finish the master refactoring if at all - any changes there @DavidBadura? Is the lib + bundle split still happening or should we abandon that?

**Comment by tolry** [comment]
weird, probably by mistake

**Comment by phansys** [comment]
Can I help? Please, don't hesitate to share your concerns.
Thank you in advance!
