### ISSUE TITLE
Unable to find template "SimpleThingsEntityAuditBundle:Audit:index.html.twig"

### ISSUE THREAD

**Issue by balvirsingh** [sonata-project/EntityAuditBundle#336]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| Used Version     | e.g. 1.0.1

I installed the bundle on both Symfony 3 and Symfony 4 versions. Installed successfully, logs are inserting successfully. But when I call the URL - 

http://localhost:3000/audit

it gives the mentioned below error - 

Unable to find template "SimpleThingsEntityAuditBundle:Audit:index.html.twig" (looked into: /home/mycomputer/htdocs/ListManagement-master/app/Resources/views, /home/mycomputer/htdocs/ListManagement-master/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).

Please suggest how can we resolve it. I also tried by adding the twig in the mentioned path but still same error.

I need to run it on Symfony 4

Thanks.

**Comment by toriqo** [comment]
add the templating engine to your framework

`framework:
    templating:
        engines: ['twig']`

**Comment by kirya-dev** [comment]
Now templating is deprecated

**Comment by wbloszyk** [comment]
It look like wrong Symfony configuration.
