### ISSUE TITLE
Integration with EasyAdminBundle ?

### ISSUE THREAD

**Issue by drupol** [sonata-project/EntityAuditBundle#426]
Hello,

I'm trying to use this amazing bundle with another amazing bundle: [EasyAdminBundle](https://symfony.com/bundles/EasyAdminBundle/current/index.html).

My project only have one entity: ```Document```.

Once this bundle has been enable, 2 new tables were created automatically: `documents_audit` and `revisions`.

I created entities out of these tables and I succeeded to use it properly with EasyAdminBundle.

However, when I delete the database and recreate it, it fails:

```
root@fa2497b77242:/srv/app# bin/console doctrine:database:create        
Created database /srv/app/var/data.db for connection named default
root@fa2497b77242:/srv/app# bin/console doctrine:schema:create   
 !                                                                                                                      
 ! [CAUTION] This operation should not be executed in a production environment!                                         
 !                                                                                                                      

 Creating database schema...


In SchemaException.php line 112:
                                                                              
  The table with name '/srv/app/var/data.db.documents_audit' already exists.  
                                                                              

doctrine:schema:create [--em EM] [--dump-sql]

root@fa2497b77242:/srv/app#
``` 

It is failing because `EntityAuditBundle` will create the tables automatically based on the existing entities, while Doctrine create the tables based on the Entity files.

And then, this is why it tries to create twice the tables. Once because of `EntityAuditBundle`, once because Doctrine has found the Entities files.

So my question now (I also asked it on Slack): What would be the best way to integrate `sonata-project/entity-audit-bundle` with EasyAdmin ?

Edit: I made a screencast of the project here : https://youtu.be/pSXwFyAVN90
The `documents_audit` and `revisions` entities were created AFTER the database has been created. And at this point, if I delete the database, I'm unable to recreate it... and this is why I created this issue initially.

**Comment by VincentLanglet** [comment]
There is nothing related to EasyAdminBundle here, just to doctrine and databases

You should rely on migration to recreate your database.

It would be better to run
```
./bin/console doctrine:migration:diff
```
rather than
```
./bin/console doctrine:schema:update --dump-sql
```

A PR can be done to improve the documentation.

**Comment by drupol** [comment]
HI @VincentLanglet ,

When I do that I have the same issue:

```
root@fa2497b77242:/srv/app# bin/console doctrine:migration:diff

In SchemaException.php line 112:
                                                                              
  The table with name '/srv/app/var/data.db.documents_audit' already exists.  
                                                                              

doctrine:migrations:diff [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--namespace NAMESPACE] [--filter-expression FILTER-EXPRESSION] [--formatted] [--line-length LINE-LENGTH] [--check-database-platform [CHECK-DATABASE-PLATFORM]] [--allow-empty-diff] [--from-empty-schema]                                                                                                                          

root@fa2497b77242:/srv/app#
```

**Comment by VincentLanglet** [comment]
To me you already messed up your base.

I only run
- doctrine:database:drop
- doctrine:database:create
- doctrine:migration:migrate
- doctrine:migration:diff

If you run schema:create you certainly have nothing more to do.

**Comment by VincentLanglet** [comment]
Problem solved, there was already an entity with a table called `documents_audit`

**Comment by drupol** [comment]
Yep, thanks for the help.
